POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld0d1eSIsImlkIjoiNWZhNTM4NmZjNWMzNzMyODVjYTI4OWUyIiwiaWF0IjoxNjA0NjYzNDE4fQ.aT9tcTENvVTlEDP_oCQRIV7ioCaejRCBuLQgd5KdoYs

{
    "author": "Top Gun",
    "title": "over the moon",
    "url": "www.HereWeGoAgain.net",
    "likes": "4531"
}